apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-rhacm-storage
provisioner: kubernetes.io/nfs
parameters:
  server: 192.168.22.1  # The NFS server IP (adjust this to your NFS server IP)
  path: /mnt/nfs-rhacm    # The path to the NFS export
